# Generated by Django 3.1.2 on 2023-05-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230509_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='vigente',
        ),
    ]
