# Generated by Django 3.1.2 on 2023-05-21 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_carrito_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosasUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_quiere_ser_suscripto', models.BooleanField(default=False)),
                ('monto_de_suscripcion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fecha_de_pago', models.DateField(blank=True, null=True)),
                ('fecha_de_inscripcion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
