# Generated by Django 3.1.2 on 2023-05-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230521_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
