# Generated by Django 3.1.2 on 2023-05-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230521_1523'),
        ('core', '0011_auto_20230521_1408'),
    ]

    operations = [
    ]
