# Generated by Django 3.1.2 on 2023-05-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230521_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='fecha_de_inscripcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
