# Generated by Django 3.1.2 on 2023-05-21 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230521_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='fecha_de_inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
