# Generated by Django 3.1.2 on 2023-05-22 00:20

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230521_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosasuser',
            name='fecha_de_inscripcion',
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='fecha_de_pago',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='monto_de_suscripcion',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=0.00),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='si_quiere_ser_suscripto',
            field=models.BooleanField(),
        ),
    ]
