# Generated by Django 3.1.2 on 2023-05-22 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_auto_20230521_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosasuser',
            name='fecha_de_inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='fecha_de_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='monto_de_suscripcion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='si_quiere_ser_suscripto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cosasuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
